#!/bin/sh

curr="."

dir() {
    if [ -f "index.html" ]
    then
	printf "Postoji index.html"
	exit
    fi

    file="index.md"

    if [ -f "$file" ]
    then
	printf "Postoji $file\n"
    else
	printf "Index of $curr\n\n" >> $file 
	if [ ! "$curr" = "." ]
	then
	    printf "0 [.](.)\n\n" >> $file
	    printf "0 [..](..)\n\n" >> $file
	fi

	for i in *
	do
	    printf "$(du -hd0 "$i" | cut -f1) [$i]($i)\n\n" >> "$file"
	done
    fi
}

index() {
    dir
    for i in *
    do
	if [ -d "$i" ]
	then
	    cd "$i"
	    curr="$curr/$i"
	    index
	    cd ..
	    curr=${curr%/*}
	fi
    done
}

main() {
    cd $1
    index
}

main $1
